CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(200) NOT NULL,
  firebase_user_id VARCHAR(500) UNIQUE NOT NULL
);

CREATE TABLE logs (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users NOT NULL,
  time TIMESTAMP DEFAULT NOW() NOT NULL,
  action VARCHAR(200) NOT NULL
);
